version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo $RUBY_27_VERSION
      - gem environment
      - cp -r /root/cache/* /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
      - gem install bundler --no-document
      - bundle config set --local with 'test'
      - bundle install -j 8
#  pre_build:
#    commands:
  build:
    commands:
      - bundle exec rspec spec --format RspecJunitFormatter --out spec/report.xml
  post_build:
    commands:
      - rm -r /root/cache/*
      - cp -r /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/* /root/cache

reports:
  rspec_reports:
    files:
      - report.xml
    base-directory: spec
    file-format: JUNITXML

cache:
  paths:
    - '/root/cache'
