version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo $RUBY_27_VERSION
      - gem install bundler --no-document
      - bundle config set --local with 'test'
      - bundle install -j $(cat /proc/cpuinfo | grep processor | wc -l)
      - eval "$(rbenv init -)"
  pre_build:
    commands:
  build:
    commands:
      - rspec spec/* --format RspecJunitFormatter --out spec/report.xml
#  post_build:
#    commands:

reports:
  rspec_reports:
    files:
      - report.xml
    base-directory: spec
    file-format: JUNITXML

cache:
  paths:
    - '/root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/**/*'
    - '/root/.rbenv/versions/2.7.2/bin/**/*'
