version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: docker_build
      buildspec: buildspec_docker.yml
#    - identifier: docker_build
#      buildspec: build2.yml
#      env:
#        variables:
#          BUILD_ID: build2
#      depend-on:
#        - rspec
