version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: rspec
      buildspec: buildspec_rspec.yml
      privileged-mode: true
    - identifier: production_image
      buildspec: buildspec_production_image.yml
      privileged-mode: true
      depend-on:
        - rspec
