version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo $RUBY_27_VERSION
      - gem environment
  pre_build:
    commands:
      - gem install bundler --no-document
      - bundle config set --local with 'test'
      - bundle install -j 8
      - gem install rspec
      - gem install rspec_junit_formatter
  build:
    commands:
      - rspec/* spec --format RspecJunitFormatter --out spec/report.xml
#  post_build:
#    commands:

reports:
  rspec_reports:
    files:
      - report.xml
    base-directory: spec
    file-format: JUNITXML

#cache:
#  paths:
#    - '/root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/**/*'
