version: 0.2
run-as: root

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $REPOSITORY_URL:latest -t $REPOSITORY_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $REPOSITORY_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag $REPOSITORY_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $REPOSITORY_URL:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URL
      - printf '[{"name":"cdk-rails-1-web","imageUri":"%s"}]' $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
