version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo $RUBY_27_VERSION
      - gem environment
      - gem install bundler
      - bundle install --with test -j 8
      - gem install rspec_junit_formatter
  pre_build:
    commands:
  build:
    commands:
      - bundle exec rspec spec/ --format RspecJunitFormatter --out spec/reports/report.xml
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  rspec_reports:
    files:
      - report.xml
    base-directory: spec/reports
    file-format: JUNITXML

cache:

