version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u7h4b1t2
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t test/rails-1:latest .
      - docker tag test/rails-1:latest public.ecr.aws/u7h4b1t2/test/rails-1:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/u7h4b1t2/test/rails-1:latest
