version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo $RUBY_27_VERSION
  pre_build:
    commands:
      - gem environment
      - gem install bundler --no-document
      - bundle config set --local with 'test'
      - bundle install -j 8
  build:
    commands:
      - bundle exec rspec spec --format RspecJunitFormatter --out spec/report.xml
#  post_build:
#    commands:
#      - echo Build completed on `date`

reports:
  rspec_reports:
    files:
      - report.xml
    base-directory: spec
    file-format: JUNITXML

cache:
  paths:
    - '/root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/**/*'
