version: "3.8"

x-base: &base
  build:
    context: .
    args:
      BUILD_ENV: development
#    cache_from:
#      - test/rails-1:latest
  environment:
    DB_HOST: db
    DB_PASSWORD: password
    RAILS_ENV: test
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  app:
    <<: *base
    ports:
      - "3000:3000"
    command: ["rspec", "--format", "RspecJunitFormatter", "--out", "/tmp/reports/rspec.xml"]
    entrypoint: ./docker/start-test.sh
    container_name: rails_1_test
    volumes:
      - ./tmp/reports:/tmp/reports

  db:
    image: postgres:12.5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: rails_1_test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  redis:
    image: redis:6.0.5
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: none
