default: &default
  adapter: postgresql
  host: host.docker.internal
  port: 5432
  user: postgres
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: rails_1_development

test:
  <<: *default
  database: rails_1_test

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
